set directory=$XDG_CACHE_HOME/vim,~/,/tmp
set backupdir=$XDG_CACHE_HOME/vim,~/,/tmp
set viminfo+=n$XDG_CACHE_HOME/vim/viminfo
set runtimepath=$XDG_CONFIG_HOME/vim,$XDG_CONFIG_HOME/vim/after,$VIM,$VIMRUNTIME

filetype plugin indent on
syntax on

set number
set relativenumber
set ruler
set wildmenu
set splitbelow
set splitright

if $TERM == 'linux'
	set background=dark
	colorscheme pablo
else
	colorscheme habamax
endif

nnoremap j  gj
nnoremap k  gk
