(((min-height . 12)
  (min-width . 30)
  (min-height-ignore . 9)
  (min-width-ignore . 12)
  (min-height-safe . 3)
  (min-width-safe . 6)
  (min-pixel-height . 324)
  (min-pixel-width . 390)
  (min-pixel-height-ignore . 243)
  (min-pixel-width-ignore . 156)
  (min-pixel-height-safe . 81)
  (min-pixel-width-safe . 78))
 vc (pixel-width . 2560)
 (pixel-height . 1381)
 (total-width . 197)
 (total-height . 51)
 (normal-height . 1.0)
 (normal-width . 1.0)
 (combination-limit . t)
 (hc (pixel-width . 2560)
     (pixel-height . 1134)
     (total-width . 197)
     (total-height . 42)
     (normal-height . 0.8211440984793628)
     (normal-width . 1.0)
     (combination-limit)
     (vc (pixel-width . 1274)
	 (pixel-height . 1134)
	 (total-width . 98)
	 (total-height . 42)
	 (normal-height . 1.0)
	 (normal-width . 0.49765625)
	 (combination-limit)
	 (leaf (pixel-width . 1274)
	       (pixel-height . 162)
	       (total-width . 98)
	       (total-height . 6)
	       (normal-height . 0.1428571428571429)
	       (normal-width . 1.0)
	       (parameters (gdb-buffer-type . gdb-memory-buffer))
	       (buffer " *gdb-placeholder*" (selected)
		       (hscroll . 0)
		       (fringes 8 8 nil nil)
		       (margins nil)
		       (scroll-bars nil 0 t nil 0 t nil)
		       (vscroll . 0)
		       (dedicated . t)
		       (point . 1)
		       (start . 1)))
	 (leaf (last . t)
	       (pixel-width . 1274)
	       (pixel-height . 972)
	       (total-width . 98)
	       (total-height . 36)
	       (normal-height . 0.8571428571428571)
	       (normal-width . 1.0)
	       (parameters (gdb-buffer-type . source))
	       (buffer " *gdb-placeholder*" (selected)
		       (hscroll . 0)
		       (fringes 8 8 nil nil)
		       (margins nil)
		       (scroll-bars nil 0 t nil 0 t nil)
		       (vscroll . 0)
		       (dedicated)
		       (point . 1)
		       (start . 1))))
     (vc (last . t)
	 (pixel-width . 1286)
	 (pixel-height . 1134)
	 (total-width . 99)
	 (total-height . 42)
	 (normal-height . 1.0)
	 (normal-width . 0.50234375)
	 (combination-limit)
	 (leaf (pixel-width . 1286)
	       (pixel-height . 162)
	       (total-width . 99)
	       (total-height . 6)
	       (normal-height . 0.1428571428571429)
	       (normal-width . 1.0)
	       (parameters (gdb-buffer-type . gdb-inferior-io))
	       (buffer " *gdb-placeholder*" (selected)
		       (hscroll . 0)
		       (fringes 8 8 nil nil)
		       (margins nil)
		       (scroll-bars nil 0 t nil 0 t nil)
		       (vscroll . 0)
		       (dedicated . t)
		       (point . 1)
		       (start . 1)))
	 (leaf (last . t)
	       (pixel-width . 1286)
	       (pixel-height . 972)
	       (total-width . 99)
	       (total-height . 36)
	       (normal-height . 0.8571428571428571)
	       (normal-width . 1.0)
	       (parameters (gdb-buffer-type . command))
	       (buffer " *gdb-placeholder*" (selected . t)
		       (hscroll . 0)
		       (fringes 8 8 nil nil)
		       (margins nil)
		       (scroll-bars nil 0 t nil 0 t nil)
		       (vscroll . 0)
		       (dedicated)
		       (point . 1)
		       (start . 1)))))
 (hc (last . t)
     (pixel-width . 2560)
     (pixel-height . 247)
     (total-width . 197)
     (total-height . 9)
     (normal-height . 0.1788559015206372)
     (normal-width . 1.0)
     (combination-limit)
     (leaf (pixel-width . 1274)
	   (pixel-height . 247)
	   (total-width . 98)
	   (total-height . 9)
	   (normal-height . 1.0)
	   (normal-width . 0.49765624999999925)
	   (parameters (gdb-buffer-type . gdb-locals-buffer)
		       )
	   (buffer " *gdb-placeholder*" (selected)
		   (hscroll . 0)
		   (fringes 8 8 nil nil)
		   (margins nil)
		   (scroll-bars nil 0 t nil 0 t nil)
		   (vscroll . 0)
		   (dedicated . t)
		   (point . 1)
		   (start . 1)))
     (leaf (pixel-width . 975)
	   (pixel-height . 247)
	   (total-width . 75)
	   (total-height . 9)
	   (normal-height . 1.0)
	   (normal-width . 0.38085937500000006)
	   (parameters (gdb-buffer-type . gdb-breakpoints-buffer))
	   (buffer " *gdb-placeholder*" (selected)
		   (hscroll . 0)
		   (fringes 8 8 nil nil)
		   (margins nil)
		   (scroll-bars nil 0 t nil 0 t nil)
		   (vscroll . 0)
		   (dedicated . t)
		   (point . 1)
		   (start . 1)))
     (leaf (last . t)
	   (pixel-width . 311)
	   (pixel-height . 247)
	   (total-width . 24)
	   (total-height . 9)
	   (normal-height . 1.0)
	   (normal-width . 0.1214843750000008)
	   (parameters (gdb-buffer-type . gdb-stack-buffer))
	   (buffer " *gdb-placeholder*" (selected)
		   (hscroll . 0)
		   (fringes 8 8 nil nil)
		   (margins nil)
		   (scroll-bars nil 0 t nil 0 t nil)
		   (vscroll . 0)
		   (dedicated . t)
		   (point . 1)
		   (start . 1)))))
