# Global properties
separator=true
separator_block_width=15

[time]
command=date "+%R"
interval=60

[date]
command=date "+%d-%m"
interval=3600

[power]
command=power_now.sh
interval=30
color=#FFC125

[temp]
command=cpu_temp.sh
interval=5
format=json

[volume]
command=volume.sh
interval=once
signal=10

[battery]
flag=False
command=battery_status.sh
interval=10
format=json

[layout]
command=layout.sh
signal=12

[gpu]
command=gpu_check.sh
interval=5
indicator=#5B5B5B
format=json

